### ISSUE TITLE
Support for bls12 381

### ISSUE THREAD

**Issue by wdcs-amitkumar** [ChihChengLiang/bls_solidity_python#1]
Thanks for such a complex implementation in python and solidity. 

Just wanted to confirm that does this smart contract supports BLS12 382 signature??

And python generates bls 12 381 public key and signature??

**Comment by ChihChengLiang** [comment]
Hi @amitcz, 

Performing BLS12-381 operations in a contract is not yet possible today, which requires the [EIP-2537](https://eips.ethereum.org/EIPS/eip-2537) network upgrade.

To generate BLS12-381 public key and signature with Python, [py_ecc](https://github.com/ethereum/py_ecc) is the way to go. Let me also shamelessly shill my [milagro_bls_binding](https://github.com/ChihChengLiang/milagro_bls_binding), which binds the performant Rust implementation [milagro_bls](https://github.com/sigp/milagro_bls) to provide fast signing and verification in Python.

**Comment by wdcs-amitkumar** [comment]
Gotcha!!

yes BLS12 381 operations are not possible,
because it is not available natively via **precompiled contract** in EVM.

but can we somehow hard code raw public key and private key and test it in solidity. ??

**Comment by wdcs-amitkumar** [comment]
Can we implement all those operation in Solidity and verify signature ??

**Comment by ChihChengLiang** [comment]
The gas cost would be prohibitively expensive to do so. To verify a signature we need to implement the pairing function, which has an [expensive loop](https://github.com/ethereum/py_ecc/blob/master/py_ecc/bls12_381/bls12_381_pairing.py#L84) that does double and add on FQ12 points.

**Comment by wdcs-amitkumar** [comment]
@ChihChengLiang 

I appreciate your help : )

I just want to perform this operation in testnet (even it is expensive).
So will it work ??

**Comment by wdcs-amitkumar** [comment]
or Is there any evm compatible chain available that has precomoiled BLS12 381 contract ??

**Comment by ChihChengLiang** [comment]
If it is the case that you are interested in running in your own net, I would say the easiest way to do it is to enable the EIP 2537 in Geth and modify the contracts in this repo accordingly. 
https://github.com/ethereum/go-ethereum/blob/d8ff53dfb8a516f47db37dbc7fd7ad18a1e8a125/core/vm/contracts.go#L96

I'm not aware of if any other evm compatible chain has implemented the similar standard.

**Comment by wdcs-amitkumar** [comment]
Last Question ::

I want to deploy a smart contract in any of Ethereum testnet(Rinkeby, Kovan, Goerli)
and signature verifiction.

Is it possible using your smart contract ??

**Comment by ChihChengLiang** [comment]
I just licensed it under MIT. Feel free to use it.

**Comment by amitcz** [comment]
I appreciate :)

Please have a look on the other issue....regarding multiply function.
**ISSUE** : Python is not able to understand from where this **multiply** function is coming from,

**Comment by wdcs-amitkumar** [comment]
> Hi @amitcz,
> 
> Performing BLS12-381 operations in a contract is not yet possible today, which requires the [EIP-2537](https://eips.ethereum.org/EIPS/eip-2537) network upgrade.
> 
> To generate BLS12-381 public key and signature with Python, [py_ecc](https://github.com/ethereum/py_ecc) is the way to go. Let me also shamelessly shill my [milagro_bls_binding](https://github.com/ChihChengLiang/milagro_bls_binding), which binds the performant Rust implementation [milagro_bls](https://github.com/sigp/milagro_bls) to provide fast signing and verification in Python.

Is it possible to do curve implementation for BLS12 381 in Smart contract ??
So that way somehow we can verifiy BLS signature in smart contracts ??

**Comment by ChihChengLiang** [comment]
@amitcz I just learned that there's this https://github.com/ralexstokes/deposit-verifier/blob/master/deposit_verifier.sol project that uses the EIP2537 precompile.
