### ISSUE TITLE
Testcase failing

### ISSUE THREAD

**Issue by wdcs-amitkumar** [ChihChengLiang/bls_solidity_python#4]
Hi !!

I tried to test signature verification. But this test is failing.

Please have a look..
Is something wrong I am doing ??

Screenshot : [Failed test case image](https://ibb.co/RB6KYfd

)

**Comment by wdcs-amitkumar** [comment]
Need your kind attention :)

The assertion is failing at **[Line 64](https://github.com/ChihChengLiang/bls_solidity_python/blob/ef6b6ec51c7bc2e0a8f1bf04448bbf5d8c4ce6cb/tests/test_bls.py#L64)**

**Comment by ChihChengLiang** [comment]
Can you confirm if #5 address this?

**Comment by wdcs-amitkumar** [comment]
yes...its fixed 

Thank you <3
Good luck from India :)
